### ISSUE TITLE
Bundle not created and hence 404 intermittently during first access after container restart

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#918] opened 2015-03-24 14:40 UTC
```
What steps will reproduce the problem?
1.Create an application page that access a WRO4J group defined in wro.xml file 
and that uses both javascript and css resources. Load both javascript and css 
bundle inside that page.
2.Start the container (i use tomcat)
3.Access the application page.
4.You may have to repeat 2-3 with intervals to see the issue as the issue is 
not always reproducible.

I would have expect that both javascript and css bundles are appropriately 
loaded. I see that at least one of those is not loaded and 404 error occurred 
instead.


I am using WRO4J 1.7.6 and on operating system Windows 7.


I am attaching log file that shows a null pointer exception occurring. Look at 
just before the end.
```

Original issue reported on code.google.com by `syedtari...@gmail.com` on 23 Jan 2015 at 2:25

Attachments:
* [log file with WRO4J error.txt](https://storage.googleapis.com/google-code-attachments/wro4j/issue-918/comment-0/log file with WRO4J error.txt)

**Comment by alexo** [comment] 2015-09-05 15:55
I believe this issue is a duplicate of #961

**Closed by alexo** 2015-09-05 15:55 UTC
Labels: auto-migrated, Type-Defect
