### ISSUE TITLE
Can't use webjar: with maven

### ISSUE THREAD

**Issue by priand** [wro4j/wro4j#947] opened 2015-05-17 20:34 UTC
I failed running a static build using maven and the jquery webjar. The goal is to run a static build consuming webjar content, without having the whole jar being included within the resulting app ( should be 'compile' or 'provided').

Reference: https://groups.google.com/forum/#!topic/wro4j/evGexToGzJs

**Comment by alexo** [comment] 2015-05-17 21:02
I can confirm that the problem is reproducible.

The workaround until a fix is available is to use the classpath uri path:
```xml
<js>classpath:META-INF/resources/webjars/jquery/2.0.0/jquery.js</js>
```

**Comment by priand** [comment] 2015-05-17 21:05
Thanks for the quick answer! Curious: what <scope> did you try with your dependency? did you try the <provided> one?

**Comment by alexo** [comment] 2015-05-17 21:14
I've tried with version 2.0.0 of the webjar. Update the classpath uri to match your version.



—

**Comment by alexo** [comment] 2015-05-18 05:18
Sorry for previous answer. The scope used was default one - compile.

**Comment by alexo** [comment] 2015-05-18 07:54
@priand I've noticed that the actual cause of the problem is the following:

```Caused by: org.webjars.MultipleMatchesException: Multiple matches found for jquery.js```

I'm not yet sure where the second jquery.js resource is coming from, but you could fix this adding the version to the webjar uri:
```
<js>webjar:2.1.4/jquery.js</js>
```
I will continue to investigate the problem. It could be either a bug in webjar locator or there are actually two resources in the classpath with the same name.

Cheers,

**Comment by Akkuzin** [comment] 2015-09-12 01:15
emberjs dependency is to blame

running plugin with following config resolves problem
```xml
<plugin>
	<groupId>ro.isdc.wro4j</groupId>
	<artifactId>wro4j-maven-plugin</artifactId>
	<version>1.7.8</version>
	<dependencies>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>emberjs</artifactId>
			<version>1.9.0-1</version>
			<exclusions>
				<exclusion>
					<groupId>org.webjars</groupId>
					<artifactId>jquery</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
	</dependencies>
</plugin>
```

**Comment by alexo** [comment] 2015-10-20 06:55
I'm closing this issue with resolution __wontfix__, since there is a working workaround.

**Closed by alexo** 2015-10-20 06:55 UTC
Labels: wontfix
