### ISSUE TITLE
1.7.9 with less4j 1.14.0 cause no viable alternative at input '[' in ruleset 

### ISSUE THREAD

**Issue by M3lkior** [wro4j/wro4j#995] opened 2015-11-23 13:43 UTC
See https://github.com/SomMeri/less4j/issues/321

It is possible to upgrade less4j to less4j-1.15.2 ?

**Comment by alexo** [comment] 2015-11-23 21:18
Sure, it is already updated in development branch: 1.8.x from where the next release will be created.

**Comment by alexo** [comment] 2015-11-24 10:08
Closing as duplicate of #989

**Closed by alexo** 2015-11-24 10:08 UTC
Labels: duplicate
