### ISSUE TITLE
wro4j-maven-plugin with JDK 9

### ISSUE THREAD

**Issue by manovotn** [wro4j/wro4j#1039] opened 2017-01-05 08:56 UTC
Hello

Part of our project([Weld](https://github.com/weld/core)) uses wro4j-maven-plugin and I started looking into JDK 9 Jigsaw (currently at EA build 148) for project builds (early adaptation). One of the obstacles is wro4j plugin causing failures. I tried versions from 1.7.7 to 1.8.0 and although there are slight differences in error output, none of them works.

So first of all, I meant to ask whether there was/is any attempt to align wro4j with JDK9? If so, how are things looking?

And finally a stacktrace I got with wro4j plugin in version 1.8.0 (kinda long, sorry):

> [ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project weld-probe-core: Execution default of goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run failed: An API incompatibility was encountered while executing ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>ro.isdc.wro4j:wro4j-maven-plugin:1.8.0
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/home/manovotn/.m2/repository/ro/isdc/wro4j/wro4j-maven-plugin/1.8.0/wro4j-maven-plugin-1.8.0.jar
[ERROR] urls[1] = file:/home/manovotn/.m2/repository/ro/isdc/wro4j/wro4j-core/1.8.0/wro4j-core-1.8.0.jar
[ERROR] urls[2] = file:/home/manovotn/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar
[ERROR] urls[3] = file:/home/manovotn/.m2/repository/commons-io/commons-io/2.4/commons-io-2.4.jar
[ERROR] urls[4] = file:/home/manovotn/.m2/repository/ro/isdc/wro4j/wro4j-extensions/1.8.0/wro4j-extensions-1.8.0.jar
[ERROR] urls[5] = file:/home/manovotn/.m2/repository/org/mozilla/rhino/1.7.7.1/rhino-1.7.7.1.jar
[ERROR] urls[6] = file:/home/manovotn/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar
[ERROR] urls[7] = file:/home/manovotn/.m2/repository/commons-pool/commons-pool/1.6/commons-pool-1.6.jar
[ERROR] urls[8] = file:/home/manovotn/.m2/repository/org/springframework/spring-web/3.1.1.RELEASE/spring-web-3.1.1.RELEASE.jar
[ERROR] urls[9] = file:/home/manovotn/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[10] = file:/home/manovotn/.m2/repository/org/springframework/spring-beans/3.1.1.RELEASE/spring-beans-3.1.1.RELEASE.jar
[ERROR] urls[11] = file:/home/manovotn/.m2/repository/org/springframework/spring-context/3.1.1.RELEASE/spring-context-3.1.1.RELEASE.jar
[ERROR] urls[12] = file:/home/manovotn/.m2/repository/org/springframework/spring-aop/3.1.1.RELEASE/spring-aop-3.1.1.RELEASE.jar
[ERROR] urls[13] = file:/home/manovotn/.m2/repository/org/springframework/spring-expression/3.1.1.RELEASE/spring-expression-3.1.1.RELEASE.jar
[ERROR] urls[14] = file:/home/manovotn/.m2/repository/org/springframework/spring-asm/3.1.1.RELEASE/spring-asm-3.1.1.RELEASE.jar
[ERROR] urls[15] = file:/home/manovotn/.m2/repository/org/springframework/spring-core/3.1.1.RELEASE/spring-core-3.1.1.RELEASE.jar
[ERROR] urls[16] = file:/home/manovotn/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar
[ERROR] urls[17] = file:/home/manovotn/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar
[ERROR] urls[18] = file:/home/manovotn/.m2/repository/com/google/javascript/closure-compiler/v20160315/closure-compiler-v20160315.jar
[ERROR] urls[19] = file:/home/manovotn/.m2/repository/com/google/javascript/closure-compiler-externs/v20160315/closure-compiler-externs-v20160315.jar
[ERROR] urls[20] = file:/home/manovotn/.m2/repository/args4j/args4j/2.0.26/args4j-2.0.26.jar
[ERROR] urls[21] = file:/home/manovotn/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar
[ERROR] urls[22] = file:/home/manovotn/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar
[ERROR] urls[23] = file:/home/manovotn/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[24] = file:/home/manovotn/.m2/repository/com/github/lltyk/dojo-shrinksafe/1.7.2/dojo-shrinksafe-1.7.2.jar
[ERROR] urls[25] = file:/home/manovotn/.m2/repository/org/jruby/jruby-core/9.0.5.0/jruby-core-9.0.5.0.jar
[ERROR] urls[26] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-netdb/1.1.5/jnr-netdb-1.1.5.jar
[ERROR] urls[27] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-enxio/0.10/jnr-enxio-0.10.jar
[ERROR] urls[28] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-x86asm/1.0.2/jnr-x86asm-1.0.2.jar
[ERROR] urls[29] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-unixsocket/0.10/jnr-unixsocket-0.10.jar
[ERROR] urls[30] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-posix/3.0.27/jnr-posix-3.0.27.jar
[ERROR] urls[31] = file:/home/manovotn/.m2/repository/com/github/jnr/jnr-constants/0.9.0/jnr-constants-0.9.0.jar
[ERROR] urls[32] = file:/home/manovotn/.m2/repository/com/github/jnr/jffi/1.2.10/jffi-1.2.10.jar
[ERROR] urls[33] = file:/home/manovotn/.m2/repository/com/github/jnr/jffi/1.2.10/jffi-1.2.10-native.jar
[ERROR] urls[34] = file:/home/manovotn/.m2/repository/org/jruby/joni/joni/2.1.9/joni-2.1.9.jar
[ERROR] urls[35] = file:/home/manovotn/.m2/repository/org/jruby/extras/bytelist/1.0.13/bytelist-1.0.13.jar
[ERROR] urls[36] = file:/home/manovotn/.m2/repository/org/jruby/jcodings/jcodings/1.0.17/jcodings-1.0.17.jar
[ERROR] urls[37] = file:/home/manovotn/.m2/repository/org/jruby/dirgra/0.3/dirgra-0.3.jar
[ERROR] urls[38] = file:/home/manovotn/.m2/repository/com/headius/invokebinder/1.7/invokebinder-1.7.jar
[ERROR] urls[39] = file:/home/manovotn/.m2/repository/com/headius/options/1.4/options-1.4.jar
[ERROR] urls[40] = file:/home/manovotn/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar
[ERROR] urls[41] = file:/home/manovotn/.m2/repository/com/martiansoftware/nailgun-server/0.9.1/nailgun-server-0.9.1.jar
[ERROR] urls[42] = file:/home/manovotn/.m2/repository/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar
[ERROR] urls[43] = file:/home/manovotn/.m2/repository/org/jruby/jruby-stdlib/9.0.5.0/jruby-stdlib-9.0.5.0.jar
[ERROR] urls[44] = file:/home/manovotn/.m2/repository/com/darrinholst/sass-java-gems/3.4.20.0/sass-java-gems-3.4.20.0.jar
[ERROR] urls[45] = file:/home/manovotn/.m2/repository/nz/co/edmi/bourbon-gem-jar/2.1.0/bourbon-gem-jar-2.1.0.jar
[ERROR] urls[46] = file:/home/manovotn/.m2/repository/me/n4u/sass/sass-gems/3.1.19/sass-gems-3.1.19.jar
[ERROR] urls[47] = file:/home/manovotn/.m2/repository/com/github/sommeri/less4j/1.17.2/less4j-1.17.2.jar
[ERROR] urls[48] = file:/home/manovotn/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar
[ERROR] urls[49] = file:/home/manovotn/.m2/repository/commons-beanutils/commons-beanutils/1.8.3/commons-beanutils-1.8.3.jar
[ERROR] urls[50] = file:/home/manovotn/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-1.7/1.3/gmaven-runtime-1.7-1.3.jar
[ERROR] urls[51] = file:/home/manovotn/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-support/1.3/gmaven-feature-support-1.3.jar
[ERROR] urls[52] = file:/home/manovotn/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-api/1.3/gmaven-feature-api-1.3.jar
[ERROR] urls[53] = file:/home/manovotn/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.3/gmaven-runtime-support-1.3.jar
[ERROR] urls[54] = file:/home/manovotn/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.3/gmaven-runtime-api-1.3.jar
[ERROR] urls[55] = file:/home/manovotn/.m2/repository/org/sonatype/gshell/gshell-io/2.0/gshell-io-2.0.jar
[ERROR] urls[56] = file:/home/manovotn/.m2/repository/com/thoughtworks/qdox/qdox/1.10/qdox-1.10.jar
[ERROR] urls[57] = file:/home/manovotn/.m2/repository/org/codehaus/groovy/groovy-all/1.7.4/groovy-all-1.7.4.jar
[ERROR] urls[58] = file:/home/manovotn/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar
[ERROR] urls[59] = file:/home/manovotn/.m2/repository/org/apache/ant/ant-launcher/1.8.2/ant-launcher-1.8.2.jar
[ERROR] urls[60] = file:/home/manovotn/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar
[ERROR] urls[61] = file:/home/manovotn/.m2/repository/org/webjars/webjars-locator/0.30/webjars-locator-0.30.jar
[ERROR] urls[62] = file:/home/manovotn/.m2/repository/org/webjars/webjars-locator-core/0.30/webjars-locator-core-0.30.jar
[ERROR] urls[63] = file:/home/manovotn/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar
[ERROR] urls[64] = file:/home/manovotn/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.3.3/jackson-databind-2.3.3.jar
[ERROR] urls[65] = file:/home/manovotn/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.3.0/jackson-annotations-2.3.0.jar
[ERROR] urls[66] = file:/home/manovotn/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.3.3/jackson-core-2.3.3.jar
[ERROR] urls[67] = file:/home/manovotn/.m2/repository/org/webjars/jshint/2.6.3-2/jshint-2.6.3-2.jar
[ERROR] urls[68] = file:/home/manovotn/.m2/repository/org/webjars/less/1.3.3/less-1.3.3.jar
[ERROR] urls[69] = file:/home/manovotn/.m2/repository/org/webjars/emberjs/1.9.0-1/emberjs-1.9.0-1.jar
[ERROR] urls[70] = file:/home/manovotn/.m2/repository/org/webjars/jquery/1.10.2-1/jquery-1.10.2-1.jar
[ERROR] urls[71] = file:/home/manovotn/.m2/repository/org/webjars/handlebars/3.0.3/handlebars-3.0.3.jar
[ERROR] urls[72] = file:/home/manovotn/.m2/repository/org/webjars/coffee-script/1.10.0/coffee-script-1.10.0.jar
[ERROR] urls[73] = file:/home/manovotn/.m2/repository/org/webjars/envjs/1.2/envjs-1.2.jar
[ERROR] urls[74] = file:/home/manovotn/.m2/repository/org/webjars/jslint/20140708-394bf29/jslint-20140708-394bf29.jar
[ERROR] urls[75] = file:/home/manovotn/.m2/repository/org/webjars/json2/20110223/json2-20110223.jar
[ERROR] urls[76] = file:/home/manovotn/.m2/repository/javax/servlet/servlet-api/2.3/servlet-api-2.3.jar
[ERROR] urls[77] = file:/home/manovotn/.m2/repository/org/sonatype/sisu/sisu-inject-bean/2.3.0/sisu-inject-bean-2.3.0.jar
[ERROR] urls[78] = file:/home/manovotn/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[79] = file:/home/manovotn/.m2/repository/org/sonatype/sisu/sisu-guava/0.9.9/sisu-guava-0.9.9.jar
[ERROR] urls[80] = file:/home/manovotn/.m2/repository/org/mockito/mockito-core/2.0.42-beta/mockito-core-2.0.42-beta.jar
[ERROR] urls[81] = file:/home/manovotn/.m2/repository/net/bytebuddy/byte-buddy/1.2.1/byte-buddy-1.2.1.jar
[ERROR] urls[82] = file:/home/manovotn/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar
[ERROR] urls[83] = file:/home/manovotn/.m2/repository/org/codehaus/plexus/plexus-utils/2.0.6/plexus-utils-2.0.6.jar
[ERROR] urls[84] = file:/home/manovotn/.m2/repository/org/sonatype/aether/aether-util/1.13.1/aether-util-1.13.1.jar
[ERROR] urls[85] = file:/home/manovotn/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.14/plexus-interpolation-1.14.jar
[ERROR] urls[86] = file:/home/manovotn/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[87] = file:/home/manovotn/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
[ERROR] urls[88] = file:/home/manovotn/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
[ERROR] urls[89] = file:/home/manovotn/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[90] = file:/home/manovotn/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar
[ERROR] urls[91] = file:/home/manovotn/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar
[ERROR] urls[92] = file:/home/manovotn/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: NullPointerException
[ERROR] -> [Help 1]

**Comment by alexo** [comment] 2017-01-05 12:48
Hi, 

there was no attempt to align it with JDK 9. 
The stacktrace doesn't seem very helpful. I'm wondering if upgrading maven version would help. 
If you are willing to help, could you try to create a build containing all maven dependencies upgraded?

Thanks,
Alex

**Comment by manovotn** [comment] 2017-01-06 09:02
I guess I could give it a go some time next week. However, my expertise with this is more on "try && see" level than anything else. I will let you know if I figured out anything.

**Comment by manovotn** [comment] 2017-01-10 14:27
I played some more with different JDK EA build versions and managed to squeeze out a better exception than the one above. It reads this:
`Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @46c0ad2d`

This basically means, you need to run Java with additional args, in this case you will need following: `--add-opens java.base/java.lang=ALL-UNNAMED` ("export" package `java.lang` from module `java.base` into unnamed module, hence making it available for reflection).
@alexo is there a way to pass JVM args to wro4j plugin? (apart from MAVEN_OPTS which are build-wide and I want to avoid that).

**Comment by alexo** [comment] 2017-01-10 15:15
@manovotn thanks for the investigation. 

Isn't it available by default as following: 
`
<configuration>
                <jvmArgs>-Xmx -Xms -XX:PermSize= -XX:MaxPermSize= -XX:+HeapDumpOnOutOfMemoryError</jvmArgs>
</configuration>
`

If not and it requires some changes on the plugin itself, then I think we could add it explicitly.

**Comment by manovotn** [comment] 2017-01-11 08:51
@alexo `<jvmArgs>` doesn't seem to be available by default. I tried several variations but to no avail. I think it needs to be added/recognized as plugin-specific option?
I am not familiar with Maven plugin development, but I suppose at some point the plugin executes a Java process and is able to pass such arguments to JVM?

**Comment by antoinesd** [comment] 2017-02-15 14:01
Looking deeper in stack trace reveals that problem comes from Mockito and cglib classes it contains.
Recnt versions of Mockito now uses ByteBuddy which is compatible with JDK 9 so switching to version 2.76 of Mockito correct the bug.
Just pushed PR #1041 to solve issue.

**Comment by alekslevin** [comment] 2017-09-21 09:46
@antoinesd if the issue is resolved, then how come i'm getting that same error?

**Comment by LunaSela** [comment] 2017-09-23 08:43
The pull request was not yet merged and there is no new release with the bug fix yet.

I am affected by this problem, too.

**Comment by sfeigl** [comment] 2017-09-30 19:29
The mentioned pull request is not enough.There are still Java 9 issues left (at least while running the test suite)

I started a branch, which is still WIP

[java_9 branch](/sfeigl/wro4j/tree/java_9)

**Comment by alexo** [comment] 2017-10-02 07:09
Thanks for your contribution. All changes have been merged.

**Comment by ispringer** [comment] 2017-10-19 02:13
Any plans for a release that will include these changes?

**Comment by sarlv** [comment] 2018-01-20 20:23
I have same error:
`[ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project spring-petclinic: Execution default of goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run failed: An API incompatibility was encountered while executing ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run: java.lang.ExceptionInInitializerError: null`

**Comment by arey** [comment] 2018-04-15 16:37
@alexo any plans for a release that will include these fix?

**Comment by ispringer** [comment] 2018-04-18 17:56
It worked for me. I added the following within the wro4j plugin element:

```
<dependencies>
    <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>2.18.0</version>
    </dependency>
</dependencies>
```

**Comment by arey** [comment] 2018-04-22 13:06
@alexo, I've tests the 1.8.1-SNAPSHOT by disabling unit tests (they are KO on my device).
This version fixe the maven build with JDK 9. It's enough for the Spring Petclinic sample application.

**Comment by bendiken** [comment] 2018-05-07 12:57
A 1.8.1 release would be most helpful, indeed.

**Comment by arey** [comment] 2018-06-02 13:03
@alexo any news of a new release?

**Comment by mricaud** [comment] 2019-03-12 17:47
I have the same problem, any "1.8.1" version coming soon ?
Bwt would the 1.8.1 be compatible with JDK 8 (so people with older java version can work on the same project as me) ?
Adding mockito-core as dependency worked for me (thanks @ispringer for the workaround)

**Comment by ppodgorsek** [comment] 2020-02-10 19:40
Wro4j 1.9.0 has been released today and is now built against OpenJDK 9, 10 and 11.

**Closed by ppodgorsek** 2020-02-10 19:40 UTC
Labels: feature, help wanted
