### ISSUE TITLE
Failed to retrieve plugin descriptor for ro.isdc.wro4j:wro4j-core:1.7.8

### ISSUE THREAD

**Issue by brcolow** [wro4j/wro4j#959] opened 2015-07-06 21:37 UTC
When running `mvn versions:display-dependency-updates` in my project folder, all dependencies specified in my `pom.xml` are checked for new versions. The only plugin/dependency that reports an error is wro4j - and this results in the mvn versions plugin not being able to check to see if there is a new version available. The full error is:

````
Failed to retrieve plugin descriptor for ro.isdc.wro4j:wro4j-core:1.7.8: Failed to parse plugin descriptor for ro.isdc.wro4j:wro4j-core:1.7.8 (/Users/brcolow/.m2/repository/ro/isdc/wro4j/wro4j-core/1.7.8/wro4j-core-1.7.8.jar): No plugin descriptor found at META-INF/maven/plugin.xml
````

The respective entry in my `pom.xml` that triggers this error is:

````xml
<plugin>
    <groupId>ro.isdc.wro4j</groupId>
    <artifactId>wro4j-maven-plugin</artifactId>
    <version>${wro4j.version}</version>
    <configuration><wroManagerFactory>ro.isdc.wro.maven.plugin.manager.factory.ConfigurableWroManagerFactory</wroManagerFactory>
        <minimize>false</minimize>
        <wroFile>${basedir}/src/main/config/wro.xml</wroFile>
        <extraConfigFile>${basedir}/src/main/config/wro.properties</extraConfigFile>
        <destinationFolder>${basedir}/target/generated-sources</destinationFolder>
        <cssDestinationFolder>${basedir}/src/main/resources/css</cssDestinationFolder>
        <targetGroups>all</targetGroups>
        <ignoreMissingResources>false</ignoreMissingResources>
        <parallelProcessing>true</parallelProcessing>
        <incrementalBuildEnabled>true</incrementalBuildEnabled>
    </configuration>
    <executions>
        <execution>
            <phase>generate-resources</phase>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
<plugin>
    <groupId>ro.isdc.wro4j</groupId>
    <artifactId>wro4j-core</artifactId>
    <version>${wro4j.version}</version>
</plugin>
````

**Comment by alexo** [comment] 2015-07-07 09:15
@brcolow I'm unable to reproduce this problem (used 2 machines, with 2 different OS: windows & linux). I think it might be related to your environment. Similar problem was answered [here](http://stackoverflow.com/questions/7819163/maven-failed-to-retrieve-plugin-descriptor-error). Let me know if you find it useful.

I'm closing this issue with invalid resolution. Feel free to reopen if you don't agree.

**Closed by alexo** 2015-07-07 09:15 UTC

**Comment by brcolow** [comment] 2015-07-07 19:40
Hmmm...that problem seems to be about people behind a proxy - I am not behind one. Furthermore, it is strange that this happens only with wro4j (I have about 15 other dependencies in that pom). I am not suggesting to reopen, though.

**Comment by alexo** [comment] 2015-07-08 08:38
strange.... Could you try deleting the wro4j artifacts from your local repo and give it another try? 
It also  interesting if other versions cause the same error?

**Comment by brcolow** [comment] 2015-07-09 05:08
Will check into this within 24 hours.

**Comment by brcolow** [comment] 2015-07-12 06:29
It happened after deleting my local repo and trying again. It also happens with v 1.7.7. Happens on Mac OS X and Windows 7.

**Comment by alexo** [comment] 2015-07-13 08:27
What maven version do you have? Since I was unable to reproduce the problem, I suspect there is something different between your and mine environment.

**Comment by brcolow** [comment] 2015-07-14 20:46
````
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T04:57:37-07:00)
Maven home: /usr/local/Cellar/maven/3.3.3/libexec
Java version: 1.8.0_60-ea, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.4", arch: "x86_64", family: "mac"
````

**Comment by alexo** [comment] 2015-07-15 08:18
I've upgraded to maven 3.3.3 and still cannot reproduce. 
But there is something that caught my attention:
```
<plugin>
    <groupId>ro.isdc.wro4j</groupId>
    <artifactId>wro4j-core</artifactId>
    <version>${wro4j.version}</version>
</plugin>
```

The wro4j-core is configured as plugin, but it is just an artifact (not a maven plugin). I think that is the problem.
