### ISSUE TITLE
New LessCss compiler version needed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wro4j/wro4j#899] opened 2015-03-24 14:40 UTC
```
What steps will reproduce the problem?
1. Download bootstrap v3.2
2. Setup a project to compile their less files
3. Compile with maven plugin

It should process this but instead its having an issue compiling the new 
lessCss feature extend. This feature was introduced in v1.4 of less so if this 
can be worked into Maven Plugin Wro4J the new v1.4 compiler, that would be 
awesome.


```

Original issue reported on code.google.com by `csales1...@gmail.com` on 6 Sep 2014 at 2:38

**Comment by alexo** [comment] 2015-04-21 08:01
duplicate of #898

**Closed by alexo** 2015-04-21 08:01 UTC
Labels: auto-migrated, duplicate, Type-Defect
