### ISSUE TITLE
NullPointerException instead of processAndMerge

### ISSUE THREAD

**Issue by busches** [wro4j/wro4j#1003] opened 2016-01-22 17:06 UTC
A different error today. Running version `1.7.9` of the wro4j-runner with the following options:

```
debug=true
minimizeEnabled=true
gzipResources=true
resourceWatcherUpdatePeriod=1000
resourceWatcherAsync=false
cacheUpdatePeriod=1000
modelUpdatePeriod=1000
parallelPreprocessing=false
connectionTimeout=2000
encoding=UTF-8
ignoreMissingResources=false
ignoreEmptyGroup=true
ignoreFailingProcessor=false
cacheGzippedContent=true
jmxEnabled=false
preProcessors=cssMinJawr,cssUrlRewriting,semicolonAppender
uriLocators=servletContext,uri,classpath
```
Exception:
```
[exec] /webdata/jenkins/jobs/CIQ_trunk_CI/workspace/static-web/WebContent/ciq-app/core.css (108545bytes) has been created!
[exec] processing group: core.js
[exec] java.lang.NullPointerException
[exec] at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:93)
[exec] at ro.isdc.wro.model.group.processor.PreProcessorExecutor.processAndMerge(PreProcessorExecutor.java:77)
[exec] at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:83)
[exec] at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
[exec] at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
[exec] at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
[exec] at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
[exec] at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
[exec] at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
[exec] at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
[exec] at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
[exec] at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
[exec] at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
[exec] null
[exec]
[exec]
[exec] =======================================
[exec] USAGE
[exec] =======================================
[exec] null
[exec] --contextFolder PATH : Folder used as a root of the context relative
[exec] resources. By default this is the user current
[exec] folder.
[exec] --destinationFolder PATH : Where to store the processed result. By default
[exec] uses the folder named [wro].
[exec] --parallel : Turns on the parallel preProcessing of resources.
[exec] This value is false by default.
[exec] --postProcessors POST_PROCESSOR : Comma separated list of post-processors
[exec] --targetGroups GROUPS : Comma separated value of the group names from
[exec] wro.xml to process. If none is provided, all
[exec] groups will be processed.
[exec] --wroConfigurationFile PATH_TO_WRO_PROPERTIES : The path to the wro.properties file. By default
[exec] the configuration file is searched inse the user
[exec] current folder.
[exec] --wroFile PATH_TO_WRO_XML : The path to the wro model file. By default the
[exec] model is searched inse the user current folder.
[exec] -c (--compressor, --preProcessors) COMPRESSOR : Comma separated list of pre-processors
[exec] -i (--ignoreMissingResources) : Ignores missing resources
[exec] -m (--minimize) : Turns on the minimization by applying compressor
```

This is the first time this error has happened for us, so no other details to give you at this time. Previously all other failures were issue #992.

**Comment by alexo** [comment] 2016-01-25 10:21
All the NPE exception have the same cause. For some reason, the execution of the runner is performed outside of the request scope which is responsible for initialization of the configurations required to perform the processing logic. I will mark this issue as duplicate...

**Comment by alexo** [comment] 2016-01-25 10:27
Duplicate of #992

**Closed by alexo** 2016-01-25 10:27 UTC
Labels: bug, duplicate
