### ISSUE TITLE
Add Content-Type header to merged files

### ISSUE THREAD

**Issue by gosuvigi** [wro4j/wro4j#997] opened 2015-12-10 16:17 UTC
In version 1.7.9, at least, when using the runtime solution filter based solution, there is no Content-Type header present in the static css and js files that are merged by wro4j and Internet Explorer does not load the css files at all.

Maybe it would be a good idea to add this header automatically.

This issue is related to https://code.google.com/p/wro4j/issues/detail?id=341

**Comment by alexo** [comment] 2015-12-11 10:43
It was fixed in 1.4.3 release. Are you sure it is still a problem in 1.7.9? 

The original issue was migrated here: #341

**Comment by gosuvigi** [comment] 2015-12-11 20:46
Yes, it was definitely there, otherwise I wouldn't have opened the ticket. I switched to the build time method of merging the files and the files are handled by Spring Boot with the appropriate headers.

**Comment by alexo** [comment] 2015-12-11 21:14
OK, I'll check it and will confirm after reproducing the problem. Thanks for noticing it.

**Comment by gosuvigi** [comment] 2015-12-14 09:23
Could you point me to the location in your code where you add this header so that I can check it using my setup?

**Comment by gosuvigi** [comment] 2015-12-14 09:43
The header is present when using Tomcat 8 but it's not there when using Weblogic 12.

**Comment by alexo** [comment] 2015-12-14 10:22
@gosuvigi  the content type is set in ResourceBundleProcessor class. It set the header for every served request. The response is servlet container agnostic, it shouldn't matter what kind of server is being used. Can you inspect the response and show the headers? You could add any other relevant information which could help to understand the problem.

**Comment by gosuvigi** [comment] 2015-12-15 09:07
Okay, you set it via ServletResponse which, in theory, should be container agnostic. The thing is that Tomcat implements this in org.apache.catalina.connector.Response while Weblogic has probably a different class which I don't have access to. It could be that there is something very specific to Weblogic and there are workarounds for this (a servlet filter or using wro4j Maven plugin) so it's not really worth it to investigate more. Thank you for your help anyway.

**Comment by alexo** [comment] 2015-12-15 09:12
I'm closing this issue as duplicate of #341

**Closed by alexo** 2015-12-15 09:12 UTC
