### ISSUE TITLE
Could not check for resource changes because: Exception during model transformation

### ISSUE THREAD

**Issue by busches** [wro4j/wro4j#996] opened 2015-11-24 19:46 UTC
We're currently using `wro4j-runner 1.7.9` and came across the following exception today:

```
processing group: bootstrap.js
processing group: bopQuickQuote.css
processing group: bopQuickQuote.js
Could not check for resource changes because: Exception during model transformation
ro.isdc.wro.WroRuntimeException: Exception during model transformation
		 at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:63)
		 at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:27)
		 at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator$1.initialize(DefaultWroModelFactoryDecorator.java:60)
		 at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator$1.initialize(DefaultWroModelFactoryDecorator.java:50)
		 at ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:33)
		 at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator.create(DefaultWroModelFactoryDecorator.java:114)
		 at ro.isdc.wro.model.factory.DefaultWroModelFactoryDecorator.create(DefaultWroModelFactoryDecorator.java:35)
		 at ro.isdc.wro.model.group.processor.GroupsProcessor.process(GroupsProcessor.java:71)
		 at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:101)
		 at ro.isdc.wro.cache.support.DefaultSynchronizedCacheStrategyDecorator.loadValue(DefaultSynchronizedCacheStrategyDecorator.java:35)
		 at ro.isdc.wro.cache.support.AbstractSynchronizedCacheStrategyDecorator.get(AbstractSynchronizedCacheStrategyDecorator.java:55)
		 at ro.isdc.wro.manager.ResourceBundleProcessor.serveProcessedBundle(ResourceBundleProcessor.java:63)
		 at ro.isdc.wro.manager.WroManager.process(WroManager.java:159)
		 at ro.isdc.wro.runner.Wro4jCommandLineRunner.doProcess(Wro4jCommandLineRunner.java:278)
		 at ro.isdc.wro.runner.Wro4jCommandLineRunner.processGroup(Wro4jCommandLineRunner.java:220)
		 at ro.isdc.wro.runner.Wro4jCommandLineRunner.process(Wro4jCommandLineRunner.java:187)
		 at ro.isdc.wro.runner.Wro4jCommandLineRunner.doMain(Wro4jCommandLineRunner.java:152)
		 at ro.isdc.wro.runner.Wro4jCommandLineRunner.main(Wro4jCommandLineRunner.java:104)
Caused by: java.lang.NullPointerException
		 at ro.isdc.wro.model.transformer.WildcardExpanderModelTransformer.processResource(WildcardExpanderModelTransformer.java:96)
		 at ro.isdc.wro.model.transformer.WildcardExpanderModelTransformer.transform(WildcardExpanderModelTransformer.java:85)
		 at ro.isdc.wro.model.transformer.WildcardExpanderModelTransformer.transform(WildcardExpanderModelTransformer.java:58)
		 at ro.isdc.wro.model.factory.ModelTransformerFactory.create(ModelTransformerFactory.java:61)
		 ... 17 more
Exception during model transformation
```

This is the first time we've run into this issue and again are not able to consistently reproduce it. :)

Configuration:
```
debug=true
minimizeEnabled=true
gzipResources=true
resourceWatcherUpdatePeriod=1000
resourceWatcherAsync=false
cacheUpdatePeriod=1000
modelUpdatePeriod=1000
parallelPreprocessing=false
connectionTimeout=2000
encoding=UTF-8
ignoreMissingResources=false
ignoreEmptyGroup=true
ignoreFailingProcessor=false
cacheGzippedContent=true
jmxEnabled=false
preProcessors=cssMinJawr,cssUrlRewriting,jsMin,semicolonAppende
uriLocators=servletContext,uri,classpath
```

We're running against JRE 6, so the POM file we're using to build the runner can found be [here](https://github.com/busches/wro4j-runner).

**Comment by alexo** [comment] 2015-11-27 16:09
I think this problem is the same as the one reported in #992 
Closing this as duplicate.

**Comment by alexo** [comment] 2015-11-27 16:09
Duplicate of #992

**Closed by alexo** 2015-11-27 16:09 UTC
Labels: bug

**Comment by alexo** [comment] 2015-11-27 16:11
@busches it would reallly help if you could provide a way which I could use to reproduce the problem. Example: the minimum amount of resources being processed, the model & configuration. Also, the operation system & jdk version being used would help.

**Comment by busches** [comment] 2015-11-30 14:30
@alexo If I had a way to reliably reproduce any of the issues, I would give them. :) I opened it as a new issue since it's a different error being thrown.

Here's the breakdown of the groups we have:

Group 1: 
- 2 css
- 10 js

Group 2:
- 1 css

Group 3:
- 1 css
- 10 js

Group 4:
- 1 css
- 2 hardcoded JS
- 1 ** js, which includes 47 files

Group 5:
- 2 js

Group 6:
- Group 1
- Group 3 
- Group 4

Group 7:
- 1 ** js, includes 21 files

Group 8:
- 1 ** js, includes 11 files
- 2 hardcoded JS

Group 9:
- 2 js

Group 10:
- 2 js

Group 11:
- 11 js

The configuration file is in a previous comment and I'm not sure of what you mean by model.

Server info:
`Linux version 2.6.32-358.14.1.el6.x86_64 (mockbuild@x86-022.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-3) (GCC) ) #1 SMP Mon Jun 17 15:54:20 EDT 2013`

Java version:
```
java version "1.6.0"
Java(TM) SE Runtime Environment (build pxi3260sr13fp2-20130424_01(SR13 FP2))
IBM J9 VM (build 2.4, JRE 1.6.0 IBM J9 2.4 Linux x86-32 jvmxi3260sr13fp2-20130423_146146 (JIT enabled, AOT enabled)
J9VM - 20130423_146146
JIT  - r9_20130108_31100ifx1
GC   - 20121212_AA)
JCL  - 20130419_01
```

Also, potentially unrelated, but if I check out the `wro4j` project clean, I can not get `mvn test` to pass on Windows, using JDK 6/7/8 and a few of the errors are the `isIgnoreFailingProcessor` error. Is that to be expected?
