### ISSUE TITLE
Upgrade handlebars processor to latest version 

### ISSUE THREAD

**Issue by msacristan** [wro4j/wro4j#943] opened 2015-05-11 11:02 UTC
Handlebars is on version 3.0.3. 

When trying to use it with the current preprocesor, it gives out this error when handlebars uses the precompiled templates

Error: Unknown template object: function

...n fileName lineNumber message name number stack".split(" ");d.prototype=Error()

**Comment by alexo** [comment] 2015-05-11 11:35
@msacristan could you try with latest version 1.7.8?

**Comment by msacristan** [comment] 2015-05-20 11:23
I updated to 1.7.8 and still got the issue.

**Comment by alexo** [comment] 2015-05-20 11:34
Could you provide a reproduction path?

**Comment by alexo** [comment] 2015-09-05 15:22
Duplicate of #964

**Closed by alexo** 2015-09-05 15:22 UTC
Labels: enhancement
