### ISSUE TITLE
[wro4j-maven-plugin] The destination folders are not refreshed in the workspace after an incremental build

### ISSUE THREAD

**Issue by soupiraille** [wro4j/wro4j#970] opened 2015-08-14 20:39 UTC
Hi.

The destination folder is not refreshed after an incremental build of the *wro4j-maven-plugin* plugin. In my case where the destination folder is explicitly `${project.build.directory}/m2e-wtp/web-resources`, this causes any generated file *not* being published to my WTP server (JBoss).

m2e indeed does not automatically refresh the target folder after a plugin build because it would be too costly; in other terms, m2e has no idea that some files have been generated by a plugin.

Please refer to this discussion: http://dev.eclipse.org/mhonarc/lists/m2e-users/msg03973.html
>m2e does not know about these files. And Maven does not know
>either. Only maven plugin that generates the files knows about them and
>**that plugin needs to communicate these changes back to m2e as explained
>in [1]**.
>[1] http://wiki.eclipse.org/M2E_compatible_maven_plugins

For that purpose, that last [link](http://wiki.eclipse.org/M2E_compatible_maven_plugins) suggest using either 
* `buildContext.newFileOutputStream( file )`
> File file = ...;
> OutputStream os = buildContext.newFileOutputStream( file );
> try
> {
>     ... write to the stream;
> }
> finally
> {
>     IOUtils.close( os );
> }

* or `buildContext.refresh( file );`
> File file = ...;
> buildContext.refresh( file );

**I've not gone into the plugin code, but do you think this is realisable?**

It is quite a pain actually to have all my generated .js and .css files automatically published to my WTP server, it would be awesome to have the *wro4j-maven-plugin* plugin follow these m2e directives.

Thank you!

**Comment by alexo** [comment] 2015-08-28 21:01
I would appreciate some help on this issue. I assume the change is required in Wro4jMojo class. I could apply the change as suggested, but I wouldn't be sure the reported problem is fixed. Additionally, you could provide a pull request with suggested fix (I will credit you with the contribution). I could also provide you with any support if required.

**Comment by alexo** [comment] 2015-08-28 21:20
I would appreciate some help on this issue. I have committed a potential fix (incomplete). It would be great if you could review the change and test it on your environment. Any feedback is appreciated.

Thanks,
Alex

**Comment by alexo** [comment] 2015-09-05 11:06
@soupiraille The issue is fixed in branch 1.7.x. It is unit tested. But it would be great if you could confirm if this build works in integration as expected.

**Closed by alexo** 2015-09-05 11:06 UTC
Labels: enhancement
