### ISSUE TITLE
Missing <head> element breaks web page on restart of container

### ISSUE THREAD

**Issue by anuja-dalal** [wro4j/wro4j#971] opened 2015-08-19 21:34 UTC
I am using wro4j as a runtime solution.

When index page is requested for the first time after restarting server, the html source that browser receives is incomplete. No error is logged on server. Checked in FF and Chrome, found same result.

Following is the source browser receives:
```
<script src='/data/assets/custom-jq-78f94e3c06517b242ee8a240288f9dae.js'></script>
<script type="text/javascript">
  $(document).ready(function() {
    $("#tabs").tabs();
  });
</script>
<script src='/data/assets/validator-d3185ce33f19d51e3422a35bb4753b0d.js'></script>
<link rel='stylesheet' href='/data/assets/main-styles-882a249eb534ddc70c3cc83c111e72fa.css' />
<link rel='stylesheet' href='/data/assets/custom-jq-5fe43173ba0707103bac2b6f0dc990b5.css' />    
  </head>
  <body>
    <div id="container">...</div>
 </body>
</html>
```
Please note : `<head>` element is missing. As a result page breaks.

If page is refreshed,   Its all ok..
```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">  
  <head>
    <title>Map</title>
    <meta http-equiv="X-UA-Compatible" content="IE=9">
    ...
  </head>
<body>
    <div id="container">...</div>
 </body>
</html>
```
The jsp file I am using looks like below, 
```
<!DOCTYPE html> 
<%@ page session="false" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ page contentType="text/html" pageEncoding="UTF-8"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="tiles" %>
<%@ taglib prefix="wro" uri="https://github.com/lifus/wro4j-runtime-taglib"%>
<html xmlns="http://www.w3.org/1999/xhtml">  
  <head>
    <title><tiles:getAsString name="title"/></title>
    <meta http-equiv="X-UA-Compatible" content="IE=9">

    <tiles:insertAttribute name="map-resources" />
    <tiles:insertAttribute name="menu-resources" />
    
    <wro:stylesheet group="main-styles" />
    <wro:stylesheet group="custom-jq" />    
  </head>
  <body>
    <div id="container">        
      <tiles:insertAttribute name="app-menu" />      
      <div class="center" style="width: 100%; height: 100%;">
        Hello World!
      </div>      
    </div>
  </body>
</html>
```
Please let me know if I can provide any further information to help.

**Comment by alexo** [comment] 2015-08-22 09:21
The html markup is not served by wro itself, it only serves js & css resources. I'm afraid the problem is somewhere else. Is the problem easily reproducible? Could you create a small quick-start project which can be used to reproduce the issue?

**Comment by anuja-dalal** [comment] 2015-08-26 20:26
Is there way to attach the zip? I have created a test project with structure matching to mine, thought it would be easy if I can send zip.

**Comment by alexo** [comment] 2015-08-26 21:34
Upload a zip to a public location or just create a github repo to host that project.

**Comment by anuja-dalal** [comment] 2015-08-28 01:46
Please find the zip shared on: https://drive.google.com/file/d/0B9O0uhXrTR9sYmxZVzlKaV9rNWc/view?usp=sharing

I have created directory structure somewhat similar to our project structure. In order to find out if wro4j and spring mvc are conflicting. I did not have war inside. If thats the problem let me know I will provide it too. I am using JBoss to deploy this war. Following are the steps I tried, while reproducing the bug.

1. Download and extract
2. Change dir to wro4j-test
3. Run mvn package
4. Put war in jboss deployment directory.
5. Important - Start the server (As this problem happens first time when server is started)
6. Use FF or chrome and see the page by url,  localhost:8080/wro4j-tst
7. Right click on page "View Page Source" , first time you will see the incomplete HTML. If you refresh the page real HTML reappears.

This test case is small so effect wont be seen directly on web page. But in our project, index page is always broken. 

Next week I will revisit this test case to see if I find more information.

**Comment by anuja-dalal** [comment] 2015-09-18 20:11
We are using webjars in our project. It appears that webjars has problem in version 1.7.8. 
There is workaround given in post https://github.com/wro4j/wro4j/issues/947
Somehow workaround for the webjar issue works for this issue as well.

**Comment by alexo** [comment] 2015-09-21 08:20
Closing this issue with "wontfix" resolution, since it has a workaround.

**Closed by alexo** 2015-09-21 08:20 UTC
Labels: wontfix
